In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from google.colab import files
import pandas as pd
import io #In all of the steps of step 7 I am checking the accuracy of all ML/DL models in Google collab

from google.colab import files
import pandas as pd
import io

print("📥 Please upload the English manually labelled file:")
uploaded_eng = files.upload()
english_filename = next(iter(uploaded_eng))
df_eng = pd.read_csv(io.BytesIO(uploaded_eng[english_filename]))

print("📥 Please upload the Dutch manually labelled file:")
uploaded_dutch = files.upload()
dutch_filename = next(iter(uploaded_dutch))
df_dutch = pd.read_csv(io.BytesIO(uploaded_dutch[dutch_filename]))


print("📥 Please upload the Combined dataset file:")
uploaded_comb = files.upload()
combined_filename = next(iter(uploaded_comb))
df_comb = pd.read_csv(io.BytesIO(uploaded_comb[combined_filename]))

# Clean datasets
df_eng = df_eng[df_eng["real_sentiment"].isin([-1, 0, 1])].dropna(subset=["Cleaned Comment Text"])
df_dutch = df_dutch[df_dutch["real_sentiment"].isin([-1, 0, 1])].dropna(subset=["Cleaned Comment Text"])
df_comb = df_comb[df_comb["real_sentiment"].isin([-1, 0, 1])].dropna(subset=["Cleaned Comment Text"])

# English
X_eng = df_eng["Cleaned Comment Text"].astype(str)
y_eng = df_eng["real_sentiment"]

# Dutch
X_dutch = df_dutch["Cleaned Comment Text"].astype(str)
y_dutch = df_dutch["real_sentiment"]

# Combined
X_comb = df_comb["Cleaned Comment Text"].astype(str)
y_comb = df_comb["real_sentiment"]

# Vectorizer
vectorizer = TfidfVectorizer(max_features=10000, ngram_range=(1, 2))

# Helper function
def run_lr(X, y, name=""):
    X_vec = vectorizer.fit_transform(X)
    X_train, X_val, y_train, y_val = train_test_split(X_vec, y, test_size=0.2, random_state=42, stratify=y)
    model = LogisticRegression(max_iter=1000, class_weight='balanced')
    model.fit(X_train, y_train)
    y_pred = model.predict(X_val)
    print(f"\n📊 Results for {name}")
    print("Accuracy:", accuracy_score(y_val, y_pred))
    print("Classification Report:\n", classification_report(y_val, y_pred, target_names=["Negative", "Neutral", "Positive"]))
    print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred))

# Run for all three
run_lr(X_eng, y_eng, "English Manual Comments")
run_lr(X_dutch, y_dutch, "Dutch Manual Comments")
run_lr(X_comb, y_comb, "Combined Manual Comments")

# Clean datasets
df_eng = df_eng[df_eng["real_sentiment"].isin([-1, 0, 1])].dropna(subset=["Cleaned Comment Text"])
df_dutch = df_dutch[df_dutch["real_sentiment"].isin([-1, 0, 1])].dropna(subset=["Cleaned Comment Text"])
df_comb = df_comb[df_comb["real_sentiment"].isin([-1, 0, 1])].dropna(subset=["Cleaned Comment Text"])

# English
X_eng = df_eng["Cleaned Comment Text"].astype(str)
y_eng = df_eng["real_sentiment"]

# Dutch
X_dutch = df_dutch["Cleaned Comment Text"].astype(str)
y_dutch = df_dutch["real_sentiment"]

# Combined
X_comb = df_comb["Cleaned Comment Text"].astype(str)
y_comb = df_comb["real_sentiment"]

# Vectorizer
vectorizer = TfidfVectorizer(max_features=10000, ngram_range=(1, 2))

# Helper function
def run_lr(X, y, name=""):
    X_vec = vectorizer.fit_transform(X)
    X_train, X_val, y_train, y_val = train_test_split(X_vec, y, test_size=0.2, random_state=42, stratify=y)
    model = LogisticRegression(max_iter=1000, class_weight='balanced')
    model.fit(X_train, y_train)
    y_pred = model.predict(X_val)
    print(f"\n📊 Results for {name}")
    print("Accuracy:", accuracy_score(y_val, y_pred))
    print("Classification Report:\n", classification_report(y_val, y_pred, target_names=["Negative", "Neutral", "Positive"]))
    print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred))

# Run for all three
run_lr(X_eng, y_eng, "English Manual Comments")
run_lr(X_dutch, y_dutch, "Dutch Manual Comments")
run_lr(X_comb, y_comb, "Combined Manual Comments")

📥 Please upload the English manually labelled file:


Saving sample_english_with_real_sentiment - sample_english_with_real_sentiment.csv-2.csv to sample_english_with_real_sentiment - sample_english_with_real_sentiment.csv-2 (5).csv
📥 Please upload the Dutch manually labelled file:


Saving Dutch_sample_manually_labelled - dutch_comments_with_mapped_sentiment.csv to Dutch_sample_manually_labelled - dutch_comments_with_mapped_sentiment (3).csv
📥 Please upload the Combined dataset file:


Saving combined_sentiment_training_data.csv to combined_sentiment_training_data (3).csv

📊 Results for English Manual Comments
Accuracy: 0.5607675906183369
Classification Report:
               precision    recall  f1-score   support

    Negative       0.52      0.58      0.55       143
     Neutral       0.46      0.46      0.46       127
    Positive       0.67      0.61      0.64       199

    accuracy                           0.56       469
   macro avg       0.55      0.55      0.55       469
weighted avg       0.57      0.56      0.56       469

Confusion Matrix:
 [[ 83  34  26]
 [ 35  58  34]
 [ 42  35 122]]

📊 Results for Dutch Manual Comments
Accuracy: 0.6086956521739131
Classification Report:
               precision    recall  f1-score   support

    Negative       0.68      0.57      0.62        84
     Neutral       0.55      0.65      0.59        71
    Positive       0.62      0.62      0.62        52

    accuracy                           0.61       207
   macro avg

In [7]:
# Install imbalanced-learn
!pip install -q imbalanced-learn

# Step 1: Imports
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE

# Step 2: Upload file
from google.colab import files
uploaded = files.upload()

import io
combined_filename = next(iter(uploaded_comb))
df_comb = pd.read_csv(io.BytesIO(uploaded_comb[combined_filename]))

# Step 3: Clean and prepare
df_comb = df_comb.dropna(subset=["Cleaned Comment Text"])
df_comb = df_comb[df_comb["real_sentiment"].isin([-1, 0, 1])]

X = df_comb["Cleaned Comment Text"]
y = df_comb["real_sentiment"]

# Step 4: Train-test split
X_train_texts, X_val_texts, y_train, y_val = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# Step 5: TF-IDF vectorization
vectorizer = TfidfVectorizer(max_features=10000)
X_train_vec = vectorizer.fit_transform(X_train_texts)
X_val_vec = vectorizer.transform(X_val_texts)

# Step 6: Apply SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train_vec, y_train)

# Step 7: Train Logistic Regression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_resampled, y_resampled)

# Step 8: Evaluate
y_pred = lr.predict(X_val_vec)

print("\n✅ Logistic Regression with SMOTE Results:\n")
print(classification_report(y_val, y_pred, target_names=["Negative", "Neutral", "Positive"]))

Saving combined_sentiment_training_data.csv to combined_sentiment_training_data (5).csv

✅ Logistic Regression with SMOTE Results:

              precision    recall  f1-score   support

    Negative       0.60      0.57      0.59       227
     Neutral       0.51      0.62      0.56       198
    Positive       0.67      0.60      0.64       251

    accuracy                           0.60       676
   macro avg       0.60      0.60      0.59       676
weighted avg       0.60      0.60      0.60       676

